### PR TITLE
Rails Project Completion (Forms)

### PR DESCRIPTION
**Pull request by mgunduz1**
You can find project information at [here](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/forms)

Project completed. We used following actions in our controller.
- Index AS root
- New & Create AS users/new
- Edit & Update AS users/:id/edit

Project doesn't contains any styling. Made for Microverse collaborative project named 'Forms'

### CODE REVIEW

**Review by MahmoudBakr23 — COMMENTED** [review]
# **INVALID 🛑**

Hello there :)
I can see the great work and effort you put into this project. But, I'm afraid you have to include a descriptive README file first to get it reviewed properly. 👍 

Good luck and happy coding. 👨‍💻💻

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required ♻🛑**

<hr>

Hello again :)
Thank you for your efforts in building this great app. You had your Linter configured, descriptive PR summary, commit messages, and README file. Also, you set up the app's routes and controllers correctly, as well as the models, validations, and forms. 💯 
However, there is always room for improvement. Please consider my following comments:-

- [ ] Please insert the /node_modules dir inside the gitignore file because now there are more than 5k changes.
- [ ] Please add the CLI ```rails db:create``` in your README before ```rails db:migrate```
- [ ] When the user is saved, it should redirect to the new form (blank) in both create and edit situations. Kindly modify that in the controller.
user_create

<hr>

## OPTIONAL

- It'd be great if you create only one partial for the form then render it inside both files the new and edit. Partials are starting with _. Ex: _form.html.erb

Please do the required changes, then ask for another CRR. 👍 
Good luck and happy coding. 👨‍💻💻

<hr>

Please feel free to contact me on Slack with the name "Mahmoud Bakr" if you had any questions.

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @mgunduz1 and @luqmanmusah 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes  👇.
- [ ] Please add the CLI `rails db:create` in your README before `rails db:migrate`. (As previous TSE suggested)
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi @mgunduz1 and @luqmanmusah  ! :wave:

#### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

#### You may merge, good luck with your next projects! :rocket:
#### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request merged**
